### PR TITLE
use strings.Fields to handle whitespace between items in list

### LINKED ISSUE #7895: List parsing for build tools doesn't handle multiple spaces correctly.
**Describe the bug**
For build parameters like `SRPM_PACK_LIST` we take a space-separated list, like `SRPM_PACK_LIST="openssl SymCrypt"`. The [code that parses](https://github.com/microsoft/CBL-Mariner/blob/2c4b506d7a1582164be7c0151ab049e7318f7dc3/toolkit/tools/internal/exe/exe.go#L58C1-L66C2) those into an array of packages doesn't handle multiple spaces between the package names.

**To Reproduce**
1. In a command-line, add multiple spaces between package names in a parameter, like `SRPM_PACK_LIST="foo   bar"`.
2. Build fails, complaining that it can't find one or more packages named `''`.

**Expected behavior**
Parsing code should handle multiple spaces.

### PR DESCRIPTION
**Pull request by tobiasb-ms**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 
For build parameters like `SRPM_PACK_LIST` we take a space-separated list, like `SRPM_PACK_LIST="openssl SymCrypt"`. Currently, the code that parses those into an array of packages doesn't handle multiple spaces between the package names. For example, if you add an extra space between the package names, like `"openssl  SymCrypt"`, it will parse it into three packages: "`openssl`", "``", and "`SymCrypt`" -- note the empty package name. This makes our build tools fail down the line, as they try to handle an empty package name.

###### Change Log  
- Updated the list parsing code to handle multiple spaces/whitespace between package names.
- Added tests.

###### Does this affect the toolchain?  

**YES**

###### Associated issues  
- fixes #7895

###### Test Methodology
- Tested locally
- Full Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=505261&view=results

### CODE REVIEW

**Review by dmcilvaney — APPROVED** [review]

File: toolkit/tools/internal/exe/exe_test.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+		},
+		{
+			name:     "mixed whitespace",
+			input:    "value1\tvalue2  value3",
+			expected: []string{"value1", "value2", "value3"},
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
```
Comment (neha170) [inline toolkit/tools/internal/exe/exe_test.go:53]: Not familiar with golang testing, so just making sure. This would show exactly which testcase failed and which passed?

Comment (dmcilvaney) [reply toolkit/tools/internal/exe/exe_test.go:53]: Hah, actually had this chat with Tobias as well. This seems to be the "recommended" form for tests.  Each sub-test will have its name printed if it fails, although unfortunately the line numbers refer back to the call to `Run()` so a bit of extra leg work is needed.
